### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by eclazi** [McjMzn/DebugSignaturesComparer#2]
When running DebugSignaturesComparerCli.exe the following error occurs. Is there some dependency missing or needs to be installed?

```
PS C:\Users\...\Downloads\DebugSignaturesComparer_v1.1.0> .\DebugSignaturesComparerCli.exe
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\...\Downloads\DebugSignaturesComparer_v1.1.0\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].
PS C:\Users\...\Downloads\DebugSignaturesComparer_v1.1.0>

```

**Comment by eclazi** [comment]
Maybe releases need to be made with self contained option - https://stackoverflow.com/a/61232023

**Comment by McjMzn** [comment]
I did not make the release build a self-contained app as that would make it significantly larger. Do you have the .NET (Core) Runtime installed?
https://dotnet.microsoft.com/download

**Comment by eclazi** [comment]
Maybe not. I built from source and visual studio installed something and now it runs.... so probably not. 

Maybe add to the readme that .net runtime is needed.

Thanks
